'use client'

import { useParams } from 'next/navigation'
import React from 'react'

// export const metadata = {
//   title: "About Us | Next App",
//   description: "Generated by create next app",
// };

export default function page() {

    const params = useParams();

  return (
    <>
      About Us
    </>
  )
}
