import ProductDetail from '@/app/Components/ProductDetail';
import React from 'react'

export const metadata = {
  title: "Product Details | Next App",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <ProductDetail/>
    </>
  )
}
