import './assets/css/style.css'
import CommonLayout from './Components/CommonLayout';
import './style.css'

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CommonLayout>
          {children}
        </CommonLayout>
      </body>
    </html>
  );
}
